Host forgejo-xvr
  HostName forgejo.pi.xvr
  User git
  Port 222
  IdentityFile ~/.ssh/forgejo
  IdentitiesOnly yes
  PreferredAuthentications publickey
  PasswordAuthentication no
  KbdInteractiveAuthentication no
  PubkeyAuthentication yes
